"""OpenAI-backed investigator with read-only tools and deterministic guardrails.

The model decides which hypotheses to inspect. The application owns data access, the visible
timeline, financial-impact calculation, human-review policy, and final report validation.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from contracts.schemas import (
    Claim,
    Evidence,
    IncidentCandidate,
    IncidentReport,
    InvestigationStep,
    ReportStatus,
)
from engine.investigator.runner import (
    MIN_CONFIRMED_CONFIDENCE,
    MIN_CONFIRMED_MARGIN,
    MIN_PROBABLE_CONFIDENCE,
    MIN_WINNER_MARGIN,
    InvestigationResult,
    report_loss_fields,
)
from engine.investigator.tools import ReadOnlyInvestigationTools
from engine.investigator.validation import ReportValidationError, validate_report

MAX_MODEL_TURNS = 10
MAX_REPORT_ATTEMPTS = 2


class AgentClaimDraft(BaseModel):
    """Strict claim shape generated by Structured Outputs."""

    model_config = ConfigDict(extra="forbid")

    claim: str = Field(min_length=1)
    evidence_ids: list[str] = Field(min_length=1)
    confidence: float = Field(ge=0, le=1)


class AgentReportDraft(BaseModel):
    """Only fields the model may decide; trusted fields are added by the application."""

    model_config = ConfigDict(extra="forbid")

    status: ReportStatus
    winning_candidate_id: str | None
    summary: str = Field(min_length=1)
    claims: list[AgentClaimDraft]
    recommended_action: str = Field(min_length=1)


TOOL_DEFINITIONS: list[dict[str, Any]] = [
    {
        "type": "function",
        "name": "rank_candidates",
        "description": (
            "Rank the root-cause candidates produced by the statistical engine. "
            "Returns candidate fields but not the underlying evidence records."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 20,
                    "description": "Maximum number of ranked candidates to return.",
                }
            },
            "required": ["limit"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_candidate_evidence",
        "description": (
            "Read every evidence record attached to one candidate. Call this before citing any "
            "of those evidence IDs."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "type": "string",
                    "description": "Candidate ID returned by rank_candidates.",
                }
            },
            "required": ["candidate_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "compare_top_candidates",
        "description": (
            "Compare the two best candidates and return their confidence and RCA-score margins."
        ),
        "parameters": {
            "type": "object",
            "properties": {},
            "required": [],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_financial_impact",
        "description": (
            "Read the candidate's deterministic affected count and estimated USD loss per hour."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "type": "string",
                    "description": "Candidate ID returned by rank_candidates.",
                }
            },
            "required": ["candidate_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "finish_investigation",
        "description": (
            "Signal that enough evidence has been inspected and the structured report can now "
            "be produced. Do not call this before ranking candidates and inspecting the evidence "
            "needed for every planned claim."
        ),
        "parameters": {
            "type": "object",
            "properties": {},
            "required": [],
            "additionalProperties": False,
        },
        "strict": True,
    },
]


INVESTIGATOR_INSTRUCTIONS = f"""
Sos un investigador de incidentes de pagos. Investigas una sola anomalia usando exclusivamente
las herramientas de lectura provistas. Stream B ya calculo las estadisticas: no las reemplaces,
no inventes datos y no atribuyas una causa solo porque suena plausible.

Flujo obligatorio:
1. Rankea las hipotesis.
2. Consulta la evidencia de la principal y de una alternativa plausible cuando exista.
3. Compara las candidatas y consulta el impacto financiero de la posible ganadora.
4. Llama finish_investigation solo cuando puedas redactar el reporte.

Cada claim debe incluir evidence_ids existentes que hayas consultado. Si la evidencia no separa
las hipotesis, devuelve inconclusive sin ganador. Usa confirmed solo con confianza >=
{MIN_CONFIRMED_CONFIDENCE:.2f} y margen >= {MIN_CONFIRMED_MARGIN:.2f}; usa probable solo con
confianza >= {MIN_PROBABLE_CONFIDENCE:.2f} y margen >= {MIN_WINNER_MARGIN:.2f}. Escribi summary,
claims y recommended_action en espanol claro. Solo recomenda acciones: nunca afirmes que fueron
ejecutadas y conserva siempre la revision humana.
""".strip()


def _step(
    anomaly_id: str,
    index: int,
    action: str,
    result_summary: str,
    candidate_id: str | None = None,
) -> InvestigationStep:
    return InvestigationStep(
        step_id=f"step_{anomaly_id}_{index:02d}",
        candidate_id=candidate_id or anomaly_id,
        timestamp=datetime.now(timezone.utc),
        action=action,
        result_summary=result_summary,
    )


def _format_action(name: str, arguments: dict[str, Any]) -> str:
    if not arguments:
        return f"{name}()"
    rendered = ", ".join(f"{key}={value}" for key, value in sorted(arguments.items()))
    return f"{name}({rendered})"


def _dispatch_tool(
    tools: ReadOnlyInvestigationTools,
    name: str,
    arguments: dict[str, Any],
) -> tuple[Any, str, str | None]:
    candidate_id = arguments.get("candidate_id")
    if name == "rank_candidates":
        result = tools.rank_candidates(limit=arguments["limit"])
        return result, f"Se obtuvieron {len(result)} hipotesis ordenadas.", None
    if name == "get_candidate_evidence":
        result = tools.get_candidate_evidence(candidate_id)
        return result, f"Se consultaron {len(result)} evidencias.", candidate_id
    if name == "compare_top_candidates":
        result = tools.compare_top_candidates()
        return result, "Se compararon las dos hipotesis principales.", None
    if name == "get_financial_impact":
        result = tools.get_financial_impact(candidate_id)
        return (
            result,
            f"Impacto estimado: USD {result['estimated_revenue_loss_usd_per_hour']:.2f}/h.",
            candidate_id,
        )
    raise ValueError(f"Unknown tool requested by model: {name}")


def _validate_decision_policy(
    draft: AgentReportDraft,
    candidates: list[IncidentCandidate] | tuple[IncidentCandidate, ...],
) -> IncidentCandidate | None:
    ranked = sorted(candidates, key=lambda candidate: candidate.rca_score, reverse=True)
    candidate_by_id = {candidate.candidate_id: candidate for candidate in candidates}

    if draft.status == ReportStatus.inconclusive:
        if draft.winning_candidate_id is not None:
            raise ReportValidationError("inconclusive reports cannot select a winner")
        return None

    winner = candidate_by_id.get(draft.winning_candidate_id or "")
    if winner is None:
        raise ReportValidationError("probable/confirmed report selected an unknown winner")

    runner_up = next(
        (candidate for candidate in ranked if candidate.candidate_id != winner.candidate_id),
        None,
    )
    margin = winner.confidence - runner_up.confidence if runner_up else 1.0
    if draft.status == ReportStatus.confirmed and (
        winner.confidence < MIN_CONFIRMED_CONFIDENCE or margin < MIN_CONFIRMED_MARGIN
    ):
        raise ReportValidationError("confirmed report does not meet confidence/margin policy")
    if draft.status == ReportStatus.probable and (
        winner.confidence < MIN_PROBABLE_CONFIDENCE or margin < MIN_WINNER_MARGIN
    ):
        raise ReportValidationError("probable report does not meet confidence/margin policy")
    return winner


def _validate_tool_workflow(
    draft: AgentReportDraft,
    tools: ReadOnlyInvestigationTools,
    candidate_count: int,
) -> None:
    calls = tools.call_records
    names = [call.name for call in calls]
    if "rank_candidates" not in names:
        raise ReportValidationError("agent tried to finish without ranking candidates")
    if draft.winning_candidate_id is None:
        return

    def called_for(name: str, candidate_id: str) -> bool:
        return any(
            call.name == name and dict(call.arguments).get("candidate_id") == candidate_id
            for call in calls
        )

    if not called_for("get_candidate_evidence", draft.winning_candidate_id):
        raise ReportValidationError("agent selected a winner without consulting its evidence")
    if not called_for("get_financial_impact", draft.winning_candidate_id):
        raise ReportValidationError("agent selected a winner without consulting its impact")
    if candidate_count > 1 and "compare_top_candidates" not in names:
        raise ReportValidationError("agent selected a winner without comparing candidates")


def _build_report(
    anomaly_id: str,
    draft: AgentReportDraft,
    candidates: list[IncidentCandidate] | tuple[IncidentCandidate, ...],
    steps: list[InvestigationStep],
) -> IncidentReport:
    winner = _validate_decision_policy(draft, candidates)
    loss_per_hour = winner.estimated_revenue_loss_usd_per_hour if winner else 0.0
    return IncidentReport(
        incident_id=f"inc_{anomaly_id}",
        anomaly_id=anomaly_id,
        generated_at=datetime.now(timezone.utc),
        status=draft.status,
        winning_candidate_id=draft.winning_candidate_id,
        summary=draft.summary,
        claims=[Claim(**claim.model_dump()) for claim in draft.claims],
        recommended_action=draft.recommended_action,
        requires_human_review=True,
        investigation_steps=[step.step_id for step in steps],
        **report_loss_fields(loss_per_hour),
    )


def run_openai_investigation(
    anomaly_id: str,
    candidates: list[IncidentCandidate] | tuple[IncidentCandidate, ...],
    evidence: list[Evidence] | tuple[Evidence, ...],
    *,
    model: str,
    client: Any | None = None,
) -> InvestigationResult:
    """Run the agent using Responses API; no request is made until this function is called."""
    if not model.strip():
        raise ValueError("model must be an explicit non-empty model ID")
    if client is None:
        from openai import OpenAI

        client = OpenAI()

    read_tools = ReadOnlyInvestigationTools(anomaly_id, candidates, evidence)
    steps: list[InvestigationStep] = []
    input_items: list[Any] = [
        {
            "role": "user",
            "content": (
                f"Investiga anomaly_id={anomaly_id}. Los datos solo estan disponibles mediante "
                "las herramientas de lectura."
            ),
        }
    ]

    finished = False
    for _ in range(MAX_MODEL_TURNS):
        response = client.responses.create(
            model=model,
            instructions=INVESTIGATOR_INSTRUCTIONS,
            input=input_items,
            tools=TOOL_DEFINITIONS,
            tool_choice="required",
            parallel_tool_calls=False,
            store=False,
        )
        input_items.extend(response.output)
        calls = [item for item in response.output if item.type == "function_call"]
        if not calls:
            raise RuntimeError("model returned no function call while tool_choice was required")

        for call in calls:
            arguments = json.loads(call.arguments)
            if call.name == "finish_investigation":
                steps.append(
                    _step(
                        anomaly_id,
                        len(steps) + 1,
                        "finish_investigation()",
                        "El agente solicito cerrar la investigacion estructurada.",
                    )
                )
                input_items.append(
                    {
                        "type": "function_call_output",
                        "call_id": call.call_id,
                        "output": "Investigation ready for structured report.",
                    }
                )
                finished = True
                break

            try:
                result, summary, candidate_id = _dispatch_tool(
                    read_tools, call.name, arguments
                )
                output = json.dumps(result, ensure_ascii=False)
            except (LookupError, RuntimeError, TypeError, ValueError) as exc:
                summary = f"La consulta fue rechazada: {exc}"
                candidate_id = arguments.get("candidate_id")
                output = json.dumps({"error": str(exc)}, ensure_ascii=False)

            steps.append(
                _step(
                    anomaly_id,
                    len(steps) + 1,
                    _format_action(call.name, arguments),
                    summary,
                    candidate_id,
                )
            )
            input_items.append(
                {
                    "type": "function_call_output",
                    "call_id": call.call_id,
                    "output": output,
                }
            )
        if finished:
            break

    if not finished:
        raise RuntimeError(f"investigation did not finish within {MAX_MODEL_TURNS} model turns")

    report_input = list(input_items)
    for attempt in range(MAX_REPORT_ATTEMPTS):
        structured_response = client.responses.parse(
            model=model,
            instructions=(
                INVESTIGATOR_INSTRUCTIONS
                + "\nAhora devolve exclusivamente el IncidentReport parcial solicitado por el schema. "
                "Copia literalmente los nombres tecnicos y valores de dimensiones obtenidos por tools."
            ),
            input=report_input,
            text_format=AgentReportDraft,
            store=False,
        )
        draft = structured_response.output_parsed
        if draft is None:
            raise RuntimeError("model did not produce a parsed incident report")

        _validate_tool_workflow(draft, read_tools, len(candidates))
        try:
            report = _build_report(anomaly_id, draft, candidates, steps)
            validate_report(
                report,
                candidates=candidates,
                evidence=evidence,
                steps=steps,
                consulted_evidence_ids=read_tools.consulted_evidence_ids,
            )
        except ReportValidationError as exc:
            if attempt + 1 >= MAX_REPORT_ATTEMPTS:
                raise
            report_input.append(
                {
                    "role": "user",
                    "content": (
                        "El validador rechazo tu reporte anterior: "
                        f"{exc}. Corregilo sin agregar hechos ni evidencia. Reporte rechazado: "
                        f"{draft.model_dump_json()}"
                    ),
                }
            )
            continue

        return InvestigationResult(
            report=report,
            steps=tuple(steps),
            consulted_evidence_ids=read_tools.consulted_evidence_ids,
            tool_calls=read_tools.call_records,
        )

    raise RuntimeError("structured report retry loop ended unexpectedly")
