import type { ReactNode } from "react";
import Link from "next/link";
import { CloudOff, LoaderCircle, SearchX } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * The four things a live surface can be, kept visually distinct on purpose.
 * Conflating "the runtime is down" with "this incident does not exist" and with
 * "nothing has happened yet" is what made the old screens read as broken when
 * they were merely quiet.
 */

function Frame({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <div
      className={cn(
        "grid place-items-center rounded-2xl border border-pharos-line bg-black/[0.14] px-6 py-12 text-center",
        className,
      )}
    >
      <div className="max-w-md">{children}</div>
    </div>
  );
}

export function LoadingState({ message, className }: { message: string; className?: string }) {
  return (
    <Frame className={className}>
      <LoaderCircle
        className="mx-auto size-5 text-pharos-accent motion-safe:animate-spin"
        aria-hidden="true"
      />
      <p className="mt-4 text-sm text-pharos-muted" role="status">
        {message}
      </p>
    </Frame>
  );
}

/**
 * Quiet is a valid, healthy state. It gets a calm treatment — never a red one —
 * so an operator can tell "nothing is wrong" from "something failed".
 */
export function EmptyState({
  title,
  body,
  icon,
  action,
  className,
}: {
  title: string;
  body: string;
  icon?: ReactNode;
  action?: ReactNode;
  className?: string;
}) {
  return (
    <Frame className={className}>
      {icon ? <div className="mx-auto mb-4 text-pharos-faint">{icon}</div> : null}
      <p className="text-sm font-semibold text-pharos-ink">{title}</p>
      <p className="mt-2 text-[13px] leading-6 text-pharos-muted">{body}</p>
      {action ? <div className="mt-5 flex justify-center">{action}</div> : null}
    </Frame>
  );
}

/**
 * The backend is unreachable. Says so plainly, shows the underlying error for an
 * operator, and offers a retry — it never falls back to invented data.
 */
export function RuntimeUnavailableState({
  error,
  onRetry,
  className,
}: {
  error?: string | null;
  onRetry?: () => void;
  className?: string;
}) {
  return (
    <Frame className={cn("border-signal-critical/25 bg-signal-critical/[0.05]", className)}>
      <CloudOff className="mx-auto size-5 text-signal-critical" aria-hidden="true" />
      <p className="mt-4 text-sm font-semibold text-pharos-ink">PHAROS runtime unavailable</p>
      <p className="mt-2 text-[13px] leading-6 text-pharos-muted">
        No data is being shown because none was received. Start the engine, or check that
        <code className="mx-1 rounded bg-black/40 px-1.5 py-0.5 text-[11px] text-pharos-ink">
          NEXT_PUBLIC_CONTROL_TOWER_API_ORIGIN
        </code>
        points at it.
      </p>
      {error ? <p className="mt-3 font-mono text-[11px] text-signal-critical/80">{error}</p> : null}
      {onRetry ? (
        <button
          type="button"
          onClick={onRetry}
          className="mt-5 inline-flex items-center gap-1.5 rounded-full border border-pharos-line bg-white/[0.04] px-4 py-2 text-xs font-semibold text-pharos-ink transition hover:bg-white/[0.08]"
        >
          Retry now
        </button>
      ) : null}
    </Frame>
  );
}

/** The runtime answered, but this particular incident is not in it. */
export function NotFoundState({ incidentId, className }: { incidentId: string; className?: string }) {
  return (
    <Frame className={className}>
      <SearchX className="mx-auto size-5 text-pharos-faint" aria-hidden="true" />
      <p className="mt-4 text-sm font-semibold text-pharos-ink">Incident not found</p>
      <p className="mt-2 text-[13px] leading-6 text-pharos-muted">
        The runtime is reachable but holds no report for
        <code className="mx-1 rounded bg-black/40 px-1.5 py-0.5 text-[11px] text-pharos-ink">{incidentId}</code>.
        It may have been generated by a different run.
      </p>
      <Link
        href="/investigations"
        className="mt-5 inline-flex items-center gap-1.5 rounded-full border border-pharos-line bg-white/[0.04] px-4 py-2 text-xs font-semibold text-pharos-ink transition hover:bg-white/[0.08]"
      >
        Back to the investigation queue
      </Link>
    </Frame>
  );
}
